name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  music-suite-ci:
    name: Music Suite CI checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - run: |
        nix-shell --pure --command "cabal update && ci"
        # nix-build ci.nix --no-out-link --argstr command "CMD"
      shell: bash
